version: "3.9"
services:
  db:
    image: postgres:16
    container_name: blog_crud_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_DB: blogdb
    ports:
      - "5433:5432"   # changed host port to 5433
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloguser -d blogdb"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data: